#!/usr/bin/env bash

cleanup() {
    kubectl delete --cascade -f k8s-iperf.yaml
}

setup() {
    kubectl create -f k8s-iperf.yaml

    until $(kubectl get pods -l app=iperf-server -o jsonpath='{.items[0].status.containerStatuses[0].ready}'); do
        echo "Waiting for iperf server to start..."
        sleep 5
    done

    SERVER=$(kubectl get pod -l app=iperf-server -o name | xargs kubectl get -o jsonpath='{.status.hostIP}')

    echo "[INFO]: Server is running on ${SERVER}"
}

execute() {
    CLIENTS=$(kubectl get pods -l app=iperf-client -o name | cut -d'/' -f2)

    for POD in ${CLIENTS}; do
        until $(kubectl get pod ${POD} -o jsonpath='{.status.containerStatuses[0].ready}'); do
            echo "Waiting for ${POD} to start..."
            sleep 5
        done
        HOST=$(kubectl get pod ${POD} -o jsonpath='{.status.hostIP}')
        kubectl exec -it ${POD} -- iperf3 -c iperf-server -T "Client on ${HOST}" $@
        echo
    done
}

# main()
setup
echo "[INFO]: Waiting for clients to start..."
sleep 30
execute
cleanup